<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Enumeradores\**" />
    <Compile Remove="Excecoes\**" />
    <EmbeddedResource Remove="Enumeradores\**" />
    <EmbeddedResource Remove="Excecoes\**" />
    <None Remove="Enumeradores\**" />
    <None Remove="Excecoes\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entidades\Externas\CoreSSO\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SME.AE.COMUM\SME.AE.Comum.csproj" />
  </ItemGroup>

</Project>
